<?php $this->layout('layout') ?>

<?php $this->start('body') ?>

<div class="container">

    <div class="row justify-content-center">

        <div class="col-12 col-md-6">

            <div class="card">
                <div class="card-header">Login</div>

                <form method="post" action="<?= url('auth.login') ?>" novalidate>
                    <div class="card-body">

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input id="email" type="email" name="email" value="<?= old('email') ?>" class="form-control <?= errors()->has('email') ? 'is-invalid' : ''?>">

                            <?php if (errors()->has('email')): ?>
                                <div class="invalid-feedback">
                                    <?= errors()->getFirst('email') ?>
                                </div>
                            <?php endif ?> 
                        </div>

                        <div class="form-group">
                            <label for="password">Senha</label>
                            <input type="password" name="password" id="password" class="form-control <?= errors()->has('password') ? 'is-invalid' : '' ?>">

                            <?php if (errors()->has('password')): ?>
                                <div class="invalid-feedback">
                                    <?= errors()->getFirst('password') ?>
                                </div>
                            <?php endif ?> 
                        </div>

                        <div class="form-group pt-3">
                            <button class="btn btn-primary btn-block" type="submit">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php $this->stop('body') ?>