<?php $this->layout('layout') ?>

<?php $this->start('body') ?>

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-12 col-sm-6">
            <div class="card">
                <form name="register" method="post" action="<?= url('reg.register') ?>">
                    <div class="card-header">Cadastro</div>

                    <div class="card-body pb-0">
                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="email">Email</label>
                                <input type="email" id="email" name="email" value="<?= old('email') ?>" 
                                    class="form-control <?= errors()->has('email') ?  'is-invalid' : '' ?>
                                ">
                                
                                <?php if (errors()->has('email')): ?>
                                <div class="invalid-feedback">
                                    <?= errors()->getFirst('email') ?>
                                </div>
                                <?php endif ?> 
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="nome">Nome</label>
                                <input type="nome" id="nome" name="nome" value="<?= old('nome') ?>" 
                                    class="form-control <?= errors()->has('name') ? 'is-invalid' : '' ?>
                                ">
                                <?php if (errors()->has('name')): ?> 
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('name') ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="cep">Cep</label>
                                <input name="cep" type="text" value="<?= old('cep') ?>" id="cep" class="form-control <?= errors()->has('cep') ? 'is-invalid' : '' ?>">

                                <?php if (errors()->has('cep')): ?> 
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('cep') ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12 col-md-6">
                                <label for="senha">Senha</label>
                                <input type="password" id="senha" name="senha" class="form-control <?= errors()->has('password') ? 'is-invalid' : '' ?>">
                                <?php if (errors()->has('password')): ?>
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('password') ?>
                                    </div>
                                <?php endif ?> 
                            </div>
                         
                            <div class="form-group col-12 col-md-6">
                                <label for="senha_confirmacao">Confirmar senha</label>
                                <input type="password" id="senha_confirmacao" name="senha_confirmacao" class="form-control <?= errors()->has('password') ? 'is-invalid' : '' ?>">
                            </div>
                        </div>

                    </div>

                    <div class="d-flex justify-content-end p-3">
                        <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php $this->stop('body') ?>