<?php $this->layout('layout') ?>

<?php $this->start('body') ?>
<section id="page-login" class="mt-5 mb-5">
<div class="container">
    <?= $this->insert("_partials/_titulo",["titulo" => "Cadastro","descricao" => ""]) ?>
    <div class="row justify-content-center mt-1">
        <div class="col-12 col-sm-6">
            <div class="card">
                <form name="registration" method="post" action="<?= url('reg.register') ?>">
                    <div class="card-body pb-0">
                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="email">Email</label>
                                <input type="email" id="email" name="email" value="<?= old('email') ?>" 
                                    class="form-control <?= errors()->has('email') ?  'is-invalid' : '' ?>
                                ">
                                
                                <?php if (errors()->has('email')): ?>
                                <div class="invalid-feedback">
                                    <?= errors()->getFirst('email') ?>
                                </div>
                                <?php endif ?> 
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="nome">Nome</label>
                                <input type="nome" id="name" name="name" value="<?= old('name') ?>" 
                                    class="form-control <?= errors()->has('name') ? 'is-invalid' : '' ?>
                                ">
                                <?php if (errors()->has('name')): ?> 
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('name') ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <label for="cep">Cep</label>
                                <input data-mask="99.999-999" name="cep" type="text" value="<?= old('cep') ?>" id="cep" class="form-control mask-cep <?= errors()->has('cep') ? 'is-invalid' : '' ?>">

                                <?php if (errors()->has('cep')): ?> 
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('cep') ?>
                                    </div>
                                <?php endif ?>
                                <input type="hidden" name="city" value="">
                                <input type="hidden" name="state" value="">
                                <input type="hidden" name="lat" value="">
                                <input type="hidden" name="lng" value="">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12 col-md-6">
                                <label for="senha">Senha</label>
                                <input type="password" id="password" name="password" class="form-control <?= errors()->has('password') ? 'is-invalid' : '' ?>">
                                <?php if (errors()->has('password')): ?>
                                    <div class="invalid-feedback">
                                        <?= errors()->getFirst('password') ?>
                                    </div>
                                <?php endif ?> 
                            </div>
                         
                            <div class="form-group col-12 col-md-6">
                                <label for="senha_confirmacao">Confirmar senha</label>
                                <input type="password" id="password_confirmation" name="password_confirmation" class="form-control <?= errors()->has('password') ? 'is-invalid' : '' ?>">
                            </div>
                        </div>

                    </div>

                    <div class="d-flex justify-content-end p-3">
                        <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</section>

<?php $this->stop('body') ?>

<?php $this->start('scripts') ?>
    <script src="<?= asset('js/jquery.mask.min.js') ?>"></script>
    <script src="<?= asset('js/location.js') ?>"></script>
<?php $this->stop('scripts') ?> 