<header class="<?= on_page("home") ? "" : "back-white" ?>">

    <div class="header-main">

        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-12 col-12"> 
                    <ul class="pull-left">
                        <li><a href="<?= url("home") ?>">Home</a></li>
                        <li><a href="#">Avaliação</a></li>
                        <li><a href="<?= url('empresas') ?>">Empresas</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-12 col-xs-12">
                    <div class="logo">
                        <a href="<?= url("home") ?>">
                            <?php if(on_page('home')) : ?>
                                <img data-white="<?= asset('images/burguer-white.svg') ?>" data-original="<?= asset('images/burguer.svg') ?>" alt="Fast Food Guru" title="Fast Food Guru" src="<?= asset('images/burguer-white.svg') ?>" />
                            <?php else : ?>
                            <img alt="Fast Food Guru" title="Fast Food Guru" src="<?= asset('images/burguer.svg') ?>" />
                            <?php endif ?>
                        </a>
                    </div>
                </div>
                <div class="col-md-5 col-sm-12 col-12">
                    <ul class="pull-right">
                        <?php if (! auth()->check()) : ?> 
                        <li>
                            <a href="<?= url('auth.showForm') ?>"><i class="fa fa-sign-in"></i>Acessar</a>
                        </li>
                        <li>
                            <a href="<?= url('reg.showForm') ?>" class="btn btn-outline-secondary">
                                <i class="fa fa-user-plus"></i>Criar Conta
                            </a>
                        </li>
                        <?php endif ?>
                        <?php if (auth()->check()) : ?> 
                        <li>
                            <a href="<?= url('profile') ?>"><i class="fa fa-user"></i>Meu Perfil</a>
                        </li>
                        <li>
                            <a href="<?= url('auth.logout') ?>">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>Sair
                            </a>
                        </li>
                        <?php endif ?> 
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>