<header>

    <div class="header-main">

        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-12"> 
                    <ul class="pull-left">
                        <?php for($i = 1;$i <= 3;$i++) : ?>
                            <li><a href="http://">Menu</a></li>
                        <?php endfor ?>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-12 col-12">
                    <ul class="pull-right">
                        <li>
                            <a href="#"><i class="fa fa-sign-in"></i>Acessar</a>
                        </li>
                        <li>
                            <a href="<?= url('reg.showForm') ?>" class="btn btn-outline-secondary">
                                <i class="fa fa-user-plus"></i>
                                Criar Conta
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>