<?php $this->layout('layout')?>
<?php $this->start('body')?>
<?= $this->insert('_partials/_section-busca') ?>

<section id="mais-empresas" class="padding-section padding-bottom">
        <div class="container">
            <?= $this->insert("_partials/_titulo",["titulo" => "Empresas","descricao" => "veja abaixo algumas empresas perto de você"]) ?>
            <?= $this->insert("_partials/_lista-empresas",['rowClass' => 'mt-3']) ?>
        </div>
</section>

<?php $this->stop('body')?>