<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">                                                   
    <title>Fast Food Guru</title>
    <link rel="stylesheet" href="<?= asset("css/bootstrap.min.css") ?>">
    <link rel="stylesheet" href="<?= asset("css/tema.css") ?>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>
<body>
    <?php $this->insert("_header",[]) ?>
    <div class="main">
        <?= $this->section('body'); ?>
    </div>
    <?php $this->insert("_footer",[]) ?>

    <!-- Botão to the top !-->
    <a href="#" class="cd-top"><i class="fa fa-chevron-up"></i></a> 
    
    <script src="<?= asset("js/jquery.min.js") ?>"></script>
    <script src="<?= asset("js/main.js") ?>"></script>
</body>
</html>