<!-- Modal Edit User -->
<div class="modal fade modal-novo-post" id="editar-perfil" method="post" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form id="form-editar-perfil" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Editar Perfil</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="id-user" name="id-user" value="<?= $user->getId() ?>">
                    <div class="form-group">
                        <label>Nome</label>
                        <input class="form-control" value="<?= $user->getName() ?>" name="nome" id="nome" required>
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <label>Cep</label>
                        <input class="form-control mask-cep" id="cep" value="" name="cep" id="cep">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <label>Senha Atual</label>
                        <input id="senha_atual" type="password" name="senha_atual" class="form-control" placeholder="Digite sua senha atual">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <label>Nova Senha</label>
                        <input id="senha" type="password" name="senha" class="form-control" placeholder="Não preencher para manter atual">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <label>Repita a Senha</label>
                        <input id="repita-senha" type="password" name="repita-senha" class="form-control" placeholder="Repita a nova senha">
                        <div class="invalid-feedback"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn"><i class="fa fa-save"></i>Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>

