<div class="row">
    <div class="col-12">
        <nav aria-label="Page navigation example">
            <ul class="pagination <?= isset($align) ? $align : "" ?>">
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
            </ul>
        </nav>
    </div>
</div>